# sudo apt update && sudo apt install curl gnupg2 lsb-release
- name: ROS2 Install dependencies for setting up sources
  apt:
    name:
      - curl
      - gnupg2
      - lsb-release
    update_cache: true
  become: true

- name: ROS2 (check ros2-latest.list)
  stat:
    path: /etc/apt/sources.list.d/ros2-latest.list
  register: ros2_latest_list

# sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
- name: ROS2 (set up your keys)
  get_url:
    url: "{{ keyserver }}"
    dest: "{{ keyring_dest }}"
  when: ros2_latest_list.stat.exists == false
  become: true

# get architecture for ros2-repo
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture

# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
- name: ROS2 (add source list)
  apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }} signed-by={{ keyring_dest }}] {{ repository }} {{ ansible_lsb.codename }} main
    state: present
    update_cache: true
  become: true

- name: ROS2 (install ros-{{ rosdistro }}-{{ package }})
  apt:
    name: ros-{{ rosdistro }}-{{ package }}
    state: latest
    update_cache: true
  become: true

- name: ROS2 (install colcon)
  apt:
    name: python3-colcon-common-extensions
    state: latest
    update_cache: true
  become: true

- name: ROS2 (install vcstool)
  apt:
    name: python3-vcstool
    state: latest
    update_cache: true
  become: true

- name: ROS2 (install rmw-cyclonedds-cpp)
  apt:
    name: ros-{{ rosdistro }}-rmw-cyclonedds-cpp
    state: latest
    update_cache: true
  become: true
